### ISSUE TITLE
Use @before to skip calling setUpErrorHandler in setUp

### ISSUE THREAD

**Issue by imbrish** [digitickets/phpunit-errorhandler#1]
See https://phpunit.de/manual/current/en/appendixes.annotations.html#appendixes.annotations.before.

Thanks for developing the trait, very useful and so simple :)

**Comment by rquadling** [comment]
Hi. Thanks for that info.

**Comment by rquadling** [comment]
New release, and updated documentation. Thanks for the feedback. Glad it is useful!!!
