### ISSUE TITLE
[Feature] assertNoError();

### ISSUE THREAD

**Issue by ellisgl** [digitickets/phpunit-errorhandler#3]
As a developer, I would like to able to test that no error has been triggered.

**Comment by rquadling** [comment]
Good suggestion. Can you checkout master and see if that is what you want?

```
    public function testNoErrorsAreCapturedWhenNoErrorsAreGenerated()
    {
        $this->assertNoErrors();
    }
```

**Comment by ellisgl** [comment]
Works like a charm! I would update the composer package and docs. =)

**Comment by rquadling** [comment]
Done the docs. Just wanted to see if it was what was needed before doing a release.

**Comment by ellisgl** [comment]
Ah - I did notice this:
$this->assertEmpty($this->errors, sprintf('$s errors generated.', number_format(count($this->errors))));

shouldn't $s be %s ?

**Comment by ellisgl** [comment]
Also here's a test case:

```
public function assertNoErrorsShouldFailWhenErrorRaised()
    {
        trigger_error('This is an error.', E_USER_WARNING);
        try
        {
            $this->assertNoErrors();
        } catch (\PHPUnit\Framework\ExpectationFailedException $ex) {
            return;
        }

        $this->fail('assertNoErrors() did not fail when error raised!');
    }
```

**Comment by rquadling** [comment]
Thank you for this excellent suggestion. See https://github.com/digitickets/phpunit-errorhandler/releases/tag/4.1.0 Packagist should have this shortly.
